language: java
jdk: oraclejdk8
sudo: required
dist: trusty
language: __sugilite__
cache:
  directories:
    - $HOME/.m2
    

before_install:
- cd crossfit-back
- export APP_VERSION=`mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec`
- echo $APP_VERSION
- cd ..

install: "/bin/true"

script:
- cd crossfit-back
- mvn clean package -Pproduction -Dmake_asset=true
- cd ..

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$APP_VERSION-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for $GIT_TAG"
  - git push -q https://$GITHUBTOKEN@github.com/keepscale/ksone --tags

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUBTOKEN
  file: crossfit-back/target/crossfit-$GIT_TAG.jar
  on:
    repo: keepscale/ksone
    tags: false
    all_branches: true
    
